version: "3"

services:
  dbase:
    image: postgres:14-alpine
    container_name: posst
    env_file: ./.env.db
    ports:
      - 5432:5432
    volumes:
      - ./db/:/var/lib/postgresql/data:z
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
